### ISSUE TITLE
发现一个越界BUG

### ISSUE THREAD

**Issue by fy0** [Vonng/ac#1]
印象中好像在V2EX看到过你的帖子，不过找不到链接了。

具体复现是这样的：

将dict.txt减少到只剩一行：
```
U-571	-*电影*-

```
另存为 dict2.txt

```go
func main() {
	ac := FromFile("dict2.txt")
	Base = ac.Base
	Check = ac.Check
	Fail = ac.Failure
	Info = ac.Output
	fmt.Println(HandleLine([]byte("U-571A")))
}
```

执行即触发，撞到了Check的边界，ac.go 62行。

```go
if t := state + int(c) + RootState; t < DictSize { // 219169484
    if state == ac.Check[t] { // 53870341
```

那么中文有没有问题呢？也有。我猜测utf值最大的一个或几个字符，在匹配成功后就会出这个问题。

**Comment by Vonng** [comment]
收到，已复现，多谢~~😄。
做题的时候就用了一个case，不少地方估计还有缺陷。
这几天我有空修复整理一下，尽量做成一个能用的库。

**Comment by mangotree2** [comment]
请问修复了吗？我用中文得逗号：`，` 也会越界；
```
if t := state + int(c) + RootState; t < DictSize { // 219169484
    if state == ac.Check[t] { // 53870341
````
同时想问下，上面得代码，DictSize是怎么得出得呢？
是Check得长度么？但是如果出现上述问题简单把DictSize改了 会无限循环。
若没时间，大佬可以给出思路或原因，我自己改下看看。

**Comment by Vonng** [comment]
Fixed by [mangotree2](/mangotree2) @ #3
